version: '3.8'

services:
  app:
    container_name: webrtc
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/src
      - /src/node_modules
    command: ["npm", "start"]