version: '3.8'

services:
  app:
    container_name: webrtc
    build: .
    ports:
      - "3000:3000"
      - "3001:3001" 
    environment:
      - NODE_ENV=production
    volumes:
      - .:/src
      - /src/node_modules
    command: ["npm", "start", "dev"]

  socket:
    container_name: socket-server
    build: .
    ports:
      - "3001:3001"  
    environment:
      - NODE_ENV=production
    volumes:
      - .:/src
      - /src/node_modules
    command: ["node", "server.js"]  